version: 1
disable_existing_loggers: no
formatters:
  default:
    (): Applications.shared.customformatterfactory
handlers:
  file:
    formatter: default
    (): Applications.shared.customfilehandler
    maxbytes: 614400
    backupcount: 6
    encoding: utf-8
loggers:
#
# Default logger.
  Default:
    level: DEBUG
    handlers: [file]
    propagate: no
#
# INFO logger.
  Info:
    level: INFO
    handlers: [file]
    propagate: no
#
# Loggers for Audio CD processing Application.
  Applications.AudioCD:
    level: DEBUG
    handlers: [file]
    propagate: no
  Applications.Database.AudioCD:
    level: WARNING
    handlers: [file]
    propagate: no
  Applications.Database.DigitalAudioFiles:
    level: INFO
    handlers: [file]
    propagate: no
#
# Logger for backup processing Application.
  Backup:
    level: DEBUG
    handlers: [file]
    propagate: no
#
# Logger for images processing Application.
  Images:
    level: DEBUG
    handlers: [file]
    propagate: no
#
# Loggers for database processing Application.
  Applications.Database.Tables:
    level: DEBUG
    handlers: [file]
    propagate: no
#
# Loggers for zip files Application.
  Applications.shared.zipfiles:
    level: DEBUG
    handlers: [file]
    propagate: no
#
# Root logger.
root:
  level: DEBUG
  handlers: [file]
