from typing import Any, Iterable, List, Optional, Tuple, Union

def bootlegalbums(db: str = ...): ...
def defaultalbums(db: str = ...): ...
def exist_albumid(albumid: str, *, db: str = ...) -> bool: ...
def get_albumdetail(db: str = ..., **kwargs: Union[bool, List[str], List[int]]): ...
def get_albumheader(db: str = ..., **kwargs: Union[bool, List[str], List[int]]): ...
def get_albumidfromalbumsort(albumsort: str, *, db: str = ...) -> Iterable[str]: ...
def get_albumidfromartistsort(artistsort: str, *, db: str = ...) -> Iterable[str]: ...
def get_albumidfromgenre(genre: str, *, db: str = ...) -> Iterable[str]: ...
def get_artists(db: str = ...): ...
def get_countries(db: str = ...) -> Iterable[Tuple[str, int]]: ...
def get_genres(db: str = ...) -> Iterable[Tuple[str, int]]: ...
def get_languages(db: str = ...) -> Iterable[Tuple[str, int]]: ...
def get_providers(db: str = ...) -> Iterable[Tuple[str, int]]: ...
def get_supports(db: str = ...) -> Iterable[Tuple[str, int]]: ...
def insert_albums(*iterables) -> int: ...
def insert_albums_fromjson(*jsonfiles) -> int: ...
def insert_defaultalbums_fromplaintext(*txtfiles, db: str = ..., encoding: str = ..., **kwargs: Any) -> int: ...
def update_albums(*keys: str, db: str = ..., **kwargs: Any) -> int: ...
def update_bootlegalbums(*keys: str, db: str = ..., **kwargs: Any) -> int: ...
def update_defaultalbums(*keys: str, db: str = ..., **kwargs: Any) -> int: ...
def update_playeddisccount(albumid: str, discid: int, *, db: str = ..., local_played: Optional[Any] = ...) -> int: ...
def update_playeddiscs(*keys: str, db: str = ..., **kwargs: Any) -> int: ...
def update_rippeddiscs(*keys: str, db: str = ..., **kwargs: Any) -> int: ...
def update_tracks(*keys: str, db: str = ..., **kwargs: Any) -> int: ...
