@ECHO off
IF DEFINED _OLD_VIRTUAL_PROMPT (
    SET "_prompt=%_OLD_VIRTUAL_PROMPT%"
    SET _OLD_VIRTUAL_PROMPT=
)
IF DEFINED _OLD_VIRTUAL_PYTHONHOME (
    SET "PYTHONHOME=%_OLD_VIRTUAL_PYTHONHOME%"
    SET _OLD_VIRTUAL_PYTHONHOME=
)
IF DEFINED _OLD_VIRTUAL_PATH (
    SET "PATH=%_OLD_VIRTUAL_PATH%"
    SET _OLD_VIRTUAL_PATH=
)
@IF DEFINED _mycp CHCP %_mycp% > NUL
PROMPT %_prompt%
SET _cp=
SET _chcp=
SET _mycp=
SET _prompt=
SET VIRTUAL_ENV=
EXIT /B 0
