bootlegalbum:
  albums: False
  bootlegs: True
  database: !!python/name:Applications.shared.DATABASE
  debug: True
  console: False
  save: True
  root: !!python/name:Applications.shared.MUSIC
  sample: True

defaultalbum:
  albums: True
  bootlegs: False
  database: !!python/name:Applications.shared.DATABASE
  debug: True
  console: False
  save: True
  root: !!python/name:Applications.shared.MUSIC
  sample: True

test_bootlegalbum:
  albums: False
  bootlegs: True
  database: !!python/name:Applications.shared.TESTDATABASE
  debug: True
  console: False
  save: True
  root: !!python/name:Applications.shared.TEMP
  sample: False

test_defaultalbum:
  albums: True
  bootlegs: False
  database: !!python/name:Applications.shared.TESTDATABASE
  debug: True
  console: False
  save: True
  root: !!python/name:Applications.shared.TEMP
  sample: False

unittest_bootlegalbum:
  albums: False
  bootlegs: True
  debug: False
  console: False
  save: False
  root: !!python/none
  sample: False

unittest_defaultalbum:
  albums: True
  bootlegs: False
  debug: False
  console: False
  save: False
  root: !!python/none
  sample: False

default:
  albums: False
  bootlegs: False
  debug: True
  console: False
  save: False
  root: !!python/none
  sample: False
