from pathlib import Path
from typing import List, Optional, Set, Union


def filter_audiofiles(cwdir: Union[str, Path], *names: str) -> Set[str]: ...
def filter_byextension(cwdir: Union[str, Path], *names: str, extensions: Optional[List[str]] = ...) -> Set[str]: ...
def filter_losslessaudiofiles(cwdir: Union[str, Path], *names: str) -> Set[str]: ...
def filter_portabledocuments(cwdir: Union[str, Path], *names: str) -> Set[str]: ...
