from pathlib import Path
from typing import List, Optional, Set, Union


filter_audiofiles = ...
filter_losslessaudiofiles = ...
filter_portabledocuments = ...


def filterfalse_(func): ...
def filter_extension(cwdir: Union[str, Path], *names: str, extension: Optional[str] = ...) -> Set[str]: ...
def filter_extensions(*extensions: str): ...
def group_(index: int = ...): ...
def match_(func): ...
