from typing import Union


def attrgetter_(name: str): ...
def contains_(*args): ...
def cvtint_(base: int = ...): ...
def eq_(value_first: Union[int, str]): ...
def int_(base: int = ...): ...
def itemgetter_(index: int = ...): ...
def lstrip_(func): ...
def lower_(func): ...
def map_(index: int): ...
def none_(func): ...
def rstrip_(func): ...
def split_(char: str): ...
def slice_(*args: int): ...
