from typing import Union


def attrgetter_(name: str): ...
def eq_(value_first: Union[int, str]): ...
def int_(base: int = ...): ...
def itemgetter_(index: int = ...): ...
def map_(index: int): ...
def split_(char: str): ...
