from typing import Any


def attrgetter_(name: str): ...
def compress_(*indexes: int): ...
def int_(base: int = ...): ...
def itemgetter_(index: int = ...): ...
def map_(index: int): ...
def partial_(*args: Any, **kwargs: Any): ...
