import logging
from abc import ABC, abstractmethod
from contextlib import ContextDecorator, ExitStack, suppress
from datetime import date, datetime
from dateutil.parser import parserinfo
from functools import singledispatch
from pathlib import PurePath, PureWindowsPath, WindowsPath
from string import Template
from typing import Any, Iterable, List, Mapping, Optional, Tuple, Union


ARTIST = ...  # type: str
APPEND = ...  # type: str
ARECA = ...  # type: str
BOOTLEGALBUM = ...  # type: str
CODEC = ...  # type: str
COMPRESSION = ...  # type: str
COPYRIGHT = ...  # type: str
DATABASE = ...  # type: str
DEFAULTALBUM = ...  # type: str
DFTDAYREGEX = ...  # type: str
DFTENCODING = ...  # type: str
DFTMONTHREGEX = ...  # ype: str
DFTTIMEZONE = ...  # type: str
DFTYEARREGEX = ...  # type: str
DISC = ...  # type: str
DRIVE = ...  # type: str
EXTENSIONS = ...  # type: Mapping[str, List[str]]
FILE = ...  # type: str
FOLDER = ...  # type: str
GENRES = ...  # type: List[str]
IMAGES = ...  # type: PurePath
IMAGES_COLLECTION = ...  # type: str
LETTER = ...  # type: str
LOCAL = ...  # type: Any
LOCALMONTHS = ...  # type: List[str]
LOGPATTERN = ...  # type: str
LOOKALBUMSORT = ...  # type: str
LOOKBOOTLEGALBUM = ...  # type: str
LOOKDEFAULTALBUM = ...  # type: str
LOOKEXTENSIONS = ...  # type: str
MUSIC = ...  # type: PurePath
TEMP = ...  # type: PurePath
TEMPLATE1 = ...  # type: str
TEMPLATE2 = ...  # type: str
TEMPLATE3 = ...  # type: str
TEMPLATE4 = ...  # type: str
TEMPLATE5 = ...  # type: str
TEMPLATE6 = ...  # type: str
TEMPLATE7 = ...  # type: str
TESTDATABASE = ...  # type: str
UPCREGEX = ...  # type: str
UTC = ...  # type: Any
UTF8 = ...  # type: str
UTF16 = ...  # type: str
UTF16BOM = ...  # type: str
WRITE = ...  # type: str
XREFERENCES = ...  # type: str


class AlternativeChangeRemoteCurrentDirectory(ContextDecorator):
    def __init__(self, ftpobj, directory: str): -> None: ...
    def __enter__(self): ...
    def __exit__(self, *exc): ...


class ChangeLocalCurrentDirectory(ContextDecorator):
    def __init__(self, directory: Union[str, PurePath]): -> None: ...
    def __enter__(self): ...
    def __exit__(self, *exc): ...


class ChangeRemoteCurrentDirectory(ContextDecorator):
    def __init__(self, ftpobj, directory) -> None: ...
    def __enter__(self): ...
    def __exit__(self, *exc): ...


class CustomHandler(logging.StreamHandler):
    def __init__(self, arg) -> None: ...


class CustomTemplate(Template):
    def __init__(self, template: str) -> None: ...


class LocalParser(parserinfo):
    def __init__(self, dayfirst: bool = ..., yearfirst: bool = ...) -> None: ...


class TemplatingEnvironment(object):
    _environment = ...  # type: Any
    def __init__(self, path, keep_trailing_newline: bool = ..., trim_blocks: bool = ..., lstrip_blocks: bool = ..., **kwarg: Any) -> None: ...
    def set_environment(self, **kwargs) -> None: ...
    def get_template(self, template: str): ...


class TitleCaseBaseConverter(ABC):
    config = ...  # type: Mapping[str, Union[List[str], bool]]
    acronyms = ...  # type: Any
    alw_lowercase = ...  # type: Any
    alw_uppercase = ...  # type: Any
    alw_capital = ...  # type: Any
    apostrophe_regex1 = ...  # type: Any
    apostrophe_regex2 = ...  # type: Any
    apostrophe_regex3 = ...  # type: Any
    apostrophe_regex4 = ...  # type: Any
    apostrophe_regex5 = ...  # type: Any
    apostrophe_regex6 = ...  # type: Any
    apostrophe_regex7 = ...  # type: Any
    capitalize_firstword = ...  # type: Any
    capitalize_lastword = ...  # type: Any
    capitalize_secondword = ...  # type: Any
    capitalize_words = ...  # type: Any
    punctuation = ...  # type: Any
    roman_numbers_regex1 = ...  # type: Any
    roman_numbers_regex2 = ...  # type: Any
    roman_numbers_regex3 = ...  # type: Any
    def __init__(self) -> None: ...
    @abstractmethod
    def convert(self, title: str) -> str: ...


class TitleCaseConverter(TitleCaseBaseConverter):
    _logger = ...  # type: Any
    def __init__(self) -> None: ...
    def convert(self, title: str) -> str: ...


class ToBoolean(object):
    _bool = ...  # type: bool
    def __init__(self, arg) -> None: ...
    @property
    def boolean_value(self) -> bool: ...


def adjust_datetime(year: int, month: int, day: int, hour: int, minutes: int, seconds: int) -> Optional[datetime]: ...
def attrgetter_(name: str): ...
def booleanify(arg): ...
def compress_(*indexes: int): ...
def convert_timestamp(timestamp: int, tz=...) -> datetime: ...
def copy(src: str, dst: str, *, size: int = ...) -> str: ...
def customfilehandler(maxbytes: int, backupcount: int, encoding: str = ...): ...
def customfilter(func, record) -> bool: ...
def customformatterfactory(pattern: str = ...): ...
def eq_string_(a: str, b: str, *, sensitive: bool = ...) -> bool: ...
def find_files(directory: Union[str, Path], *, excluded=...) -> Iterable[str]: ...
def format_collection(collection: Iterable[Tuple[Any, ...]], *, tabsize: int = ..., gap: int = ..., group: Optional[int] = ...) -> Iterable[Tuple[str, ...]]: ...
def format_date(dt: Union[date, datetime], *, template: str = ...) -> str: ...
def get_albums(directory: Union[PureWindowsPath, WindowsPath, str]) -> Iterable[Tuple[str, str, str, bool]]: ...
def get_artists(directory: str = ...) -> Iterable[Tuple[str, str]]: ...
def get_dataframe(collection: Iterable[Tuple[Any, ...]], headers: List[str]): ...
def get_dirname(path: str, *, level: int = ...) -> str: ...
def get_drives() -> Iterable[str]: ...
def get_folders(directory: str) -> Iterable[Tuple[str, str]]: ...
def get_nearestmultiple(length: int, *, multiple: int = ...) -> int: ...
def get_readabledate(dt: datetime, *, template: str = ..., tz=...) -> str: ...
def get_rippingapplication(*, timestamp: Optional[int] = ...) -> Tuple[str, Optional[int]]: ...
def get_tabs(length: int, *, tabsize: int = ...) -> str: ...
def groupby(iterable, index: int): ...
def grouper(iterable, n: int, *, fillvalue: Optional[Any] = ...): ...
def int_(base: int = ...): ...
def itemgetter_(index: int = ...): ...
def iter_collection(collection: Iterable[Tuple[Any, ...]], headers: Optional[Iterable[str]], *, char: str = ..., tabsize: int = ..., gap: int = ..., group: Optional[int] = ...) -> Iterable[str]: ...
def localize_date(dt: datetime, tz=...) -> datetime: ...
def mainscript(strg: str, align: str = ..., fill: str = ..., length: int = ...) -> str: ...
def nested_(*functions): ...
def nested_groupby(iterable, *args): ...
def normalize(strg: str) -> str: ...
def normalize2(strg: str) -> str: ...
def now(*, template: str = ...) -> str: ...
def partial_(*args, **kwargs): ...
def partitioner(iterable, *, predicate=...): ...
def pprint_count(*iterables: Tuple[str, int], length: int = ...) -> Tuple[str, str]: ...
def pprint_mapping(*iterables: Tuple[Union[int, str], Union[int, str]]) -> Iterable[Tuple[str, Union[int, str]]]: ...
def pprint_sequence(*items: Union[int, str]) -> Iterable[str]: ...
def rjustify(strg: str, width: int, *, char: str = ...) -> str: ...
def sort_by_insertion(*items: Any, reverse: bool = ...) -> Iterable[Any]: ...
def stringify(arg) -> str: ...
def valid_albumid(albumid: str) -> str: ...
def valid_albumsort(albumsort: str) -> str: ...
def valid_database(database: str) -> str: ...
def valid_datetime(arg) -> Tuple[int, datetime, Tuple[int, int, int, int, int, int, int, int, int, str, int]]: ...
def valid_discnumber(discnumber: Union[int, str]) -> int: ...
def valid_genre(genre: str) -> str: ...
def valid_path(path: str) -> str: ...
def valid_productcode(productcode: str) -> str: ...
def valid_tracks(tracks: Union[int, str]) -> int: ...
def valid_year(year: Union[int, str]) -> int: ...
