# Configuration file for MyPythonProject/GUI/Sources/03/main.py
# Update _FIELDS if _HEADERS change.
# Update _SORTFIELDS if _HEADERS change.
# Update _SELECTORS if _FIELDS change.
_CALLABLES:
  defaultalbums: !!python/name:Applications.Tables.Albums.shared.update_defaultalbums
  rippeddiscs: !!python/name:Applications.Tables.Albums.shared.update_rippeddiscs

_CLASSES:
 defaultalbums: !!python/name:Applications.interfaces.DefaultAlbumRecord
 rippeddiscs: !!python/name:Applications.interfaces.RippedDiscRecord

_DFTSORTFIELDS:
  bootlegalbums:
    - 1
    - - 2
      - 13
      - 7
  defaultalbums:
    - 1
    - - 2
      - 13
      - 8
  rippeddiscs:
    - 4
    - []

_DISPLAYEDFIELDS:
  defaultalbums:
    - artistsort
    - albumsort
    - origyear
    - year
    - album
    - label
    - upc
    - genre
    - discs
  rippeddiscs:
    - artistsort
    - albumsort
    - disc
    - tracks
    - album
    - genre
    - unixtimestamp
    - rippeddate

_ENABLEDFIELDS:
  defaultalbums:
    origyear: true
    year: true
    album: true
    label: true
    upc: true
  rippeddiscs:
    unixtimestamp: true

_FIELDS:
  bootlegalbums: 16
  defaultalbums: 16
  rippeddiscs: 11

_HEADERS:
  bootlegalbums:
    - ArtistSort
    - AlbumSort
    - BootlegTrackDate
    - BootlegTrackTour
    - BootlegTrackCity
    - BootlegTrackCountry
    - UnixTimestamp
    - CreatedDate
    - Album
    - Genre
    - Support
    - IsBootleg
    - Disc
    - Discs
    - IsLive
    - Tracks
  defaultalbums:
    - ArtistSort
    - AlbumSort
    - OrigYear
    - Year
    - Album
    - Label
    - UPC
    - UnixTimestamp
    - CreatedDate
    - Genre
    - Support
    - IsBootleg
    - Disc
    - Discs
    - IsLive
    - Tracks
  rippeddiscs:
    - ArtistSort
    - AlbumSort
    - Disc
    - UnixTimestamp
    - RippedDate
    - RippedYear
    - RippedMonth
    - Album
    - Genre
    - IsBootleg
    - Tracks

_MAPPINGS:
  defaultalbums:
    origyear:
      - origyear
      - !!python/name:int
    year:
      - year
      - !!python/name:int
  rippeddiscs:
    unixtimestamp:
      - ripped
      - !!python/name:Applications.interfaces.adapt_timestamp

_SELECTORS:
  bootlegalbums:
    - 0
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 0
  defaultalbums:
    - 0
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 0
  rippeddiscs:
    - 0
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 0
    - 0

_SIZES:
  defaultalbums:
    - 9
    - 2
    - 9
    - 25
  rippeddiscs:
    - 8
    - 2
    - 9
    - 25

_SORTFIELDS:
  defaultalbums:
    default:
      - 1
      - 2
      - 13
      - 8
    !!str 1:
      - 2
      - 13
      - 8
    !!str 2:
      - 1
      - 13
      - 8
    !!str 8:
      - 1
      - 2
      - 13
    !!str 13:
      - 1
      - 2
      - 8
  rippeddiscs:
    default:
      - 1
      - 2
      - 3
      - 4
    !!str 1:
      - 2
      - 3
      - 4
    !!str 2:
      - 1
      - 3
      - 4
    !!str 3:
      - 1
      - 2
      - 4
    !!str 6:
      - 7
      - 1
      - 2
      - 3
      - 4
    !!str 7:
      - 6
      - 1
      - 2
      - 3
      - 4

_TABLES:
  default:
    - Albums
    - DefaultAlbums
    - BootlegAlbums
    - RippedDiscs
    - PlayedDiscs
  "G:\\Computing\\MyPythonProject\\Applications\\Tests\\database.db":
    - Albums
    - DefaultAlbums
    - BootlegAlbums
    - RippedDiscs
    - PlayedDiscs
