from pathlib import Path
from typing import Any, Iterator, Tuple, Union

REGEX: Any = ...

def format_collection(*iterables, start: int = ...) -> Iterator[Tuple[str, int, str]]: ...
def format_menu(*iterables: Tuple[str, int, Any], group: int = ...) -> Iterator[str]: ...
def get_targets(path: Union[Path, str]) -> Iterator[Tuple[str, int]]: ...
