version: 1
disable_existing_loggers: no

formatters:
  default:
    (): Applications.shared.customformatterfactory

handlers:

  file:
    formatter: default
    level: DEBUG
    (): Applications.shared.customfilehandler
    maxbytes: 614400
    backupcount: 9
    encoding: utf-8

  console:
    class: logging.StreamHandler
    stream: ext://sys.stdout
    formatter: default
    level: INFO

loggers:

# Logger for backup tasks.
  Backup:
    level: INFO
    handlers: [file]
    propagate: no

# Logger for main scripts.
  MyPythonProject:
    level: INFO
    handlers: [file]
    propagate: no

# Loggers for Audio CD processing Applications.
  Applications.AudioCD:
    level: INFO
    handlers: [file]
    propagate: no

# Loggers for tables processing Applications.
  Applications.Tables.Albums:
    level: DEBUG
    handlers: [file]
    propagate: no
  Applications.Tables.Bootlegs:
    level: INFO
    handlers: [file]
    propagate: no
  Applications.Tables.RippedDiscs:
    level: INFO
    handlers: [file]
    propagate: no
  Applications.Tables.Tasks:
    level: INFO
    handlers: [file]
    propagate: no

# Logger for unittest modules.
  Applications.Tests:
    level: DEBUG
    handlers: [file]
    propagate: no

# Root logger.
root:
  level: DEBUG
  handlers: [file]
