version: 1
disable_existing_loggers: false

formatters:
  default:
    (): Applications.shared.customformatterfactory

handlers:

  file:
    formatter: default
    level: DEBUG
    (): Applications.shared.customfilehandler
    maxbytes: 614400
    backupcount: 9
    encoding: utf-8

  console:
    formatter: default
    level: INFO
    (): Applications.shared.CustomHandler
    arg: true
    func: !!python/name:Applications.shared.customfilter

loggers:

# Loggers for Audio CDs processing scripts.
  Applications.AudioCD:
    level: DEBUG
    handlers: [file]
    propagate: false

# Loggers for tables processing scripts.
  Applications.Tables.Albums:
    level: INFO
    handlers: [file]
    propagate: false
  Applications.Tables.RippedDiscs:
    level: INFO
    handlers: [file]
    propagate: false
  Applications.Tables.Tasks:
    level: INFO
    handlers: [file]
    propagate: false
  Applications.Tables:
    level: INFO
    handlers: [file]
    propagate: false

# Logger for unittest modules.
  Applications.Unittests:
    level: DEBUG
    handlers: [file]
    propagate: false

# Logger for global shared classes and functions.
  Applications.shared:
    level: INFO
    handlers: [file]
    propagate: false

# Logger for main scripts.
  MyPythonProject:
    level: INFO
    handlers: [file]
    propagate: false

# Root logger.
root:
  level: DEBUG
  handlers: [file]
